BaseUrl: "https://agchen28.github.io/"
LanguageCode: "zh-cn"
Title: "EdisonChen Blog"
menu:
  main:
      - Name: "首页"
        Weight: 1
        URL: "/"
      - Name: "正经的"
        Weight: 2
        URL: "/categories/正经的/"
      - Name: "捡垃圾"
        Weight: 3
        URL: "/categories/捡垃圾/"
      - Name: "关于"
        Weight: 100
        URL: "/about"

Params:
  Author: "Edison Chen"
  ShowRelatedPost: True
  SyntaxHighlightTheme: "github.min.css"
  dateformat: "2006年01月02日"
  readMore: false
  section: false
  articleFooter: false
  latests: true
  showCategory: true
  Summary: false

Indexes:
  tag: "tags"
  category: "categories"
permalinks:
  post: /blog/:slug/
  
MetadataFormat: "yaml"
